import type { Country } from './types';

export const GAME_SETTINGS = {
  ARENA_SIZE: 400, // in pixels
  FLAG_WIDTH: 24,
  FLAG_HEIGHT: 16,
  INITIAL_SPEED: 2.5,
  ELIMINATOR_SPEED: 0.5, // degrees per frame
  ELIMINATOR_GAP_SIZE: 36, // degrees (10% of 360)
  ELIMINATOR_RADIUS_RATIO: 0.8, // 80% of the arena radius
  ELIMINATOR_THICKNESS: 2, // in pixels
  COLLISION_BOOST: 1.01, // Multiplier for velocity on collision
  MIN_SPEED: 0.5, // Minimum speed for flags to prevent them from stopping
};

export const COUNTRIES: Country[] = [
    { name: 'United States', code: 'us' },
    { name: 'Canada', code: 'ca' },
    { name: 'Mexico', code: 'mx' },
    { name: 'Brazil', code: 'br' },
    { name: 'Argentina', code: 'ar' },
    { name: 'United Kingdom', code: 'gb' },
    { name: 'France', code: 'fr' },
    { name: 'Germany', code: 'de' },
    { name: 'Italy', code: 'it' },
    { name: 'Spain', code: 'es' },
    { name: 'Portugal', code: 'pt' },
    { name: 'Russia', code: 'ru' },
    { name: 'China', code: 'cn' },
    { name: 'Japan', code: 'jp' },
    { name: 'South Korea', code: 'kr' },
    { name: 'India', code: 'in' },
    { name: 'Australia', code: 'au' },
    { name: 'South Africa', code: 'za' },
    { name: 'Egypt', code: 'eg' },
    { name: 'Nigeria', code: 'ng' },
    { name: 'Saudi Arabia', code: 'sa' },
    { name: 'United Arab Emirates', code: 'ae' },
    { name: 'Turkey', code: 'tr' },
    { name: 'Greece', code: 'gr' },
    { name: 'Sweden', code: 'se' },
    { name: 'Norway', code: 'no' },
    { name: 'Denmark', code: 'dk' },
    { name: 'Finland', code: 'fi' },
    { name: 'Netherlands', code: 'nl' },
    { name: 'Belgium', code: 'be' },
    { name: 'Switzerland', code: 'ch' },
    { name: 'Austria', code: 'at' },
    { name: 'Poland', code: 'pl' },
    { name: 'Ukraine', code: 'ua' },
    { name: 'Ireland', code: 'ie' },
    { name: 'New Zealand', code: 'nz' },
    { name: 'Singapore', code: 'sg' },
    { name: 'Malaysia', code: 'my' },
    { name: 'Thailand', code: 'th' },
    { name: 'Vietnam', code: 'vn' },
    { name: 'Indonesia', code: 'id' },
    { name: 'Philippines', code: 'ph' },
    { name: 'Pakistan', code: 'pk' },
    { name: 'Bangladesh', code: 'bd' },
    { name: 'Iran', code: 'ir' },
    { name: 'Iraq', code: 'iq' },
    { name: 'Israel', code: 'il' },
    { name: 'Chile', code: 'cl' },
    { name: 'Colombia', code: 'co' },
    { name: 'Peru', code: 'pe' },
    { name: 'Venezuela', code: 've' },
    { name: 'Cuba', code: 'cu' },
    { name: 'Jamaica', code: 'jm' },
    { name: 'Haiti', code: 'ht' },
    { name: 'Dominican Republic', code: 'do' },
    { name: 'Czech Republic', code: 'cz' },
    { name: 'Hungary', code: 'hu' },
    { name: 'Romania', code: 'ro' },
    { name: 'Bulgaria', code: 'bg' },
    { name: 'Serbia', code: 'rs' },
    { name: 'Croatia', code: 'hr' },
    { name: 'Slovenia', code: 'si' },
    { name: 'Slovakia', code: 'sk' },
    { name: 'Bosnia and Herzegovina', code: 'ba' },
    { name: 'Morocco', code: 'ma' },
    { name: 'Algeria', code: 'dz' },
    { name: 'Tunisia', code: 'tn' },
    { name: 'Libya', code: 'ly' },
    { name: 'Kenya', code: 'ke' },
    { name: 'Ethiopia', code: 'et' },
    { name: 'Tanzania', code: 'tz' },
    { name: 'Ghana', code: 'gh' },
    { name: 'Senegal', code: 'sn' },
    { name: 'Ivory Coast', code: 'ci' },
    { name: 'Cameroon', code: 'cm' },
    { name: 'Qatar', code: 'qa' },
    { name: 'Kuwait', code: 'kw' },
    { name: 'Oman', code: 'om' },
    { name: 'Bahrain', code: 'bh' },
    { name: 'Jordan', code: 'jo' },
    { name: 'Lebanon', code: 'lb' },
    { name: 'Syria', code: 'sy' },
    { name: 'Kazakhstan', code: 'kz' },
    { name: 'Uzbekistan', code: 'uz' },
    { name: 'Turkmenistan', code: 'tm' },
    { name: 'Afghanistan', code: 'af' },
    { name: 'Nepal', code: 'np' },
    { name: 'Sri Lanka', code: 'lk' },
    { name: 'Myanmar', code: 'mm' },
    { name: 'Cambodia', code: 'kh' },
    { name: 'Laos', code: 'la' },
    { name: 'Mongolia', code: 'mn' },
    { name: 'North Korea', code: 'kp' },
    { name: 'Taiwan', code: 'tw' },
    { name: 'Hong Kong', code: 'hk' },
    { name: 'Uruguay', code: 'uy' },
    { name: 'Paraguay', code: 'py' },
    { name: 'Ecuador', code: 'ec' },
    { name: 'Costa Rica', code: 'cr' },
    { name: 'Panama', code: 'pa' },
];